### ISSUE TITLE
The example to generate Json format text doesn't work as expected

### ISSUE THREAD

**Issue by Yuxing0610** [epfl-dlab/transformers-CFG#10]
When running the `generate_json.py` as demonstrated in the readme file, the output is weird: 

![image](https://github.com/epfl-dlab/transformers-CFG/assets/91256274/f0526237-80d9-40f8-892b-7067fa3f6d43)

- The output is not the same as shown in the comments of the file
- The second part of the output doesn't seem to be in JSON format with the mismatched braces and double quotes as well as the strange comment at the end of the string.

**Comment by Saibo-creator** [comment]
Hey @Yuxing0610, thanks for bringing this up. Upon looking into the issue you mentioned, we discovered that the quality of the output was being adversely affected by an overly large repetition penalty setting.

By adjusting the repetition penalty to `1.1`, you'll achieve the output you were expecting:

```
['This is a valid json string for http request:{ "http://example.com/api_key" : { "id": 1, "name":"my-request", "url": "https:/s3.amazonaws.com/v1/accounts/user?token=', 'This is a valid json string for shopping cart:{ "name": { "price": 0.5, "type":"item", "value": 1 }, "description" : { "price": 2.0 }}']
```
I've gone ahead and updated the example script to reflect this adjustment to a 1.1 repetition penalty.

To explain further, when the repetition penalty is set too high, it hampers the model's ability to reuse tokens that have already appeared. This could lead to incomplete outputs, such as missing closing brackets or quotation marks, hence the odd and truncated results you observed.

However, it's worth noting that, technically, the output you encountered does not violate the JSON format, even though it may appear unconventional.
