### ISSUE TITLE
`_accept_string` vs `_accept_prefix`

### ISSUE THREAD

**Issue by arinaruck** [epfl-dlab/transformers-CFG#13]
Hi! 
Currently the `recognizer._accept_string` verifies if the input string is a valid prefix within a grammar rather than a valid sentence of the grammar.

e.g. with simple EBNF grammar:
```
root ::= chain
chain ::= ( bond? atom )+ 
bond ::=  "-" 
atom ::=  "C"
```

The string "C-" gets accepted since it is a prefix of valid sentences within the grammar (e.g. "C-C").
Is it possible to also add a method that verifies that the sting is a valid sentence? 
Such that for the simple grammar above `recognizer._accept_string("C-", ...)`  returns `False`, while `recognizer._accept_string("C-C", ...)`  returns `True`?

Thanks!

**Comment by Saibo-creator** [comment]
Hello @arinaruck 
Thanks for raising this point !
The `_accept_string` method accepts not only a complete string but also a partial matching string. 
To avoid ambiguity, I renamed it to `_accept_prefix` and add a new `_accept_string` method which only accept complete string.

check: https://github.com/epfl-dlab/transformers-CFG/blob/main/transformers_cfg/recognizer.py#L373
and https://github.com/epfl-dlab/transformers-CFG/blob/main/transformers_cfg/recognizer.py#L379
