### ISSUE TITLE
Link to demo doesn't work

### ISSUE THREAD

**Issue by ineiti** [epfl-dlab/transformers-CFG#35]
Hi,

I tried the link to the [Demo with JSON Grammar](https://huggingface.co/spaces/saibo/transformers-CFG-JSON-demo), but huggingface reports an error:

> failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to create new parent process: namespace path: lstat /proc/0/ns/ipc: no such file or directory: unknown

**Comment by Saibo-creator** [comment]
Hello, thanks for reporting this issue. We just restarted the container and now it should be back to normal: https://huggingface.co/spaces/saibo/transformers-CFG-JSON-demo

**Comment by ineiti** [comment]
Great - you're running the container on your own server, or does it run on Huggingface?
