### ISSUE TITLE
Debugger modules/functions missing

### ISSUE THREAD

**Issue by clache547** [epfl-dlab/transformers-CFG#53]
https://github.com/epfl-dlab/transformers-CFG/blob/9c2aaf33c98c86cb7f8509d4c0a28aadb3f96c8d/docs/debugging_custom_grammars.md?plain=1#L93

I get an error when trying to import GrammarRecognizer, and when I checked it doesn't seem to exist in the newest version. I looked at previous versions and saw it in version 0.1.3, but then `_accept_prefix` doesn't seem to exist.

**Comment by Saibo-creator** [comment]
Hello @clache547 ,
Thank you for raising this issue and for your investigation. You are correct; we renamed the class `GrammarRecognizer` to `StringRecognizer` but did not update this document. Here is the new version, which I will correct in the relevant PR:
       
```python
from transformers_cfg.parser import parse_ebnf
from transformers_cfg.recognizer import StringRecognizer

with open("examples/grammars/json.ebnf", "r") as file:
    input_text = file.read()
parsed_grammar = parse_ebnf(input_text)

start_rule_id = parsed_grammar.symbol_table["root"]
recognizer = StringRecognizer(parsed_grammar.grammar_encoding, start_rule_id)

# Test the grammar with a simple input
json_input = '{"foo": "bar", "baz": "bat"}'
is_accepted = recognizer._accept_prefix(json_input)
print(is_accepted)
```
It runs correctly on my side.
