### ISSUE TITLE
Mistake

### ISSUE THREAD

**Issue by timvieira** [epfl-dlab/transformers-CFG#64]
There is a mistake on https://github.com/epfl-dlab/transformers-CFG/blob/5f3772588bd2424eb27451bd6e400b7286630044/transformers_cfg/tokenization/mapping.py#L136

```python
    def _map(self, token_id: int) -> str:
        raw_token = super()._map(token_id)
        # if the token is hex, token is a string like "<0x00>"
        # first 256 tokens are hex
        if raw_token.startswith("<0x"):
            #hex_value = raw_token[4:-1]             # <<<<<<<<<<<<< INCORRECT
            hex_value = raw_token[3:-1]              # <<<<<<<<<<<<< CORRECTED
            raw_token = chr(int(hex_value, 16))
        return raw_token
```

Sanity check:
```python
>>> raw_token = "<0x32>"
>>> raw_token[3:-1] 
'32'
>>> raw_token[4:-1]
'2'
```

**Comment by Saibo-creator** [comment]
Thank you @timvieira  for pointing out this :)
I fixed it in the latest refactoring of tokenization interface  https://github.com/epfl-dlab/transformers-CFG/blob/main/transformers_cfg/tokenization/middle/ByteProxyMapping.py#L58

**Comment by timvieira** [comment]
Awesome - thanks!

**Comment by timvieira** [comment]
Awesome - thanks!
