### ISSUE TITLE
Avoid computing the full mask at each step, lazy computing is better

### ISSUE THREAD

**Issue by Saibo-creator** [epfl-dlab/transformers-CFG#69]
Currently the implementation computes the full next-allowed-token mask at each decoding step according to the grammar and the prefix. 
However, in many cases, the model's most likely token is probably valid so computing the entire mask is unnecessary. 

Instead, iterately validate tokens with highest likelihood until finding the first match would probably be better. 

This would need some refactoring in the logit processor class.

**Comment by nathanrchn** [comment]
starting working on this for this week.

**Comment by Saibo-creator** [comment]
solved in #101
