### ISSUE TITLE
Key error: 'Pretokenizers' 

### ISSUE THREAD

**Issue by velocity33** [epfl-dlab/transformers-CFG#76]
After attempting to run the example code present on the repo I ran into the following error.  Any suggestions on how to proceed? My install was through PIP. and my model file contains a locally downloaded model (https://huggingface.co/mistralai/Mistral-7B-v0.1)

, line 24, in <module> grammar = IncrementalGrammarConstraint(grammar_str, "root", tokenizer) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/conda/envs/CFG/lib/python3.11/site-packages/transformers_cfg/grammar_utils.py", line 13, in __init__ super().__init__(*args, **kwargs) File "/opt/conda/envs/CFG/lib/python3.11/site-packages/transformers_cfg/token_grammar_recognizer.py", line 167, in __init__ super().__init__(grammar_str, tokenizer, start_rule_name, unicode) File "/opt/conda/envs/CFG/lib/python3.11/site-packages/transformers_cfg/token_grammar_recognizer.py", line 36, in __init__ self.unicode_trie = ByteTrie.from_tokenizer(tokenizer, unicode=unicode) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/conda/envs/CFG/lib/python3.11/site-packages/transformers_cfg/tokenization/trie.py", line 60, in from_tokenizer mapping = get_mapping(tokenizer, unicode=unicode) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/conda/envs/CFG/lib/python3.11/site-packages/transformers_cfg/tokenization/mapping.py", line 12, in get_mapping log.debug(f"tokenizer model type: {get_tokenizer_model_type(tokenizer)}") ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/conda/envs/CFG/lib/python3.11/site-packages/transformers_cfg/utils.py", line 90, in get_tokenizer_model_type or tokenizer_json["pre_tokenizer"]["pretokenizers"][1]["type"] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^ KeyError: 'pretokenizers'

**Comment by Saibo-creator** [comment]
@velocity33  Thanks for bringing this up! The issue was due to the PYPI version being quite outdated. I should have set up automatic updates for PyPI sooner, but it took longer than expected. Now, I just setup the auto push to PyPI and you can simply run `pip install -U transformers-cfg` to get the latest stable version.

**Comment by velocity33** [comment]
Apologies for the late response and thank you for your reply. After applying that fix and running with forced CPU things began to work. However when I set "cuda" as the device, I get the following issue:

Using device: cuda
Loading checkpoint shards: 100%|████████████████████████████████| 2/2 [00:03<00:00,  1.65s/it]
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
/opt/conda/envs/CFG/lib/python3.11/site-packages/transformers/generation/utils.py:1885: UserWarning: You are calling .generate() with the `input_ids` being on a device type different than your model's device. `input_ids` is on cpu, whereas the model is on cuda. You may experience unexpected behaviors or slower generation. Please make sure that you have put `input_ids` to the correct device by calling for example input_ids = input_ids.to('cuda') before running `.generate()`.
  warnings.warn(
Traceback (most recent call last):
  File "/home/[redacted]/Development/[redacted]/[redacted]CFG/transformers-CFGtest.py", line 33, in <module>
    output = model.generate(
             ^^^^^^^^^^^^^^^
  File "/opt/conda/envs/CFG/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/CFG/lib/python3.11/site-packages/transformers/generation/utils.py", line 2024, in generate
    result = self._sample(
             ^^^^^^^^^^^^^
  File "/opt/conda/envs/CFG/lib/python3.11/site-packages/transformers/generation/utils.py", line 2982, in _sample
    outputs = self(**model_inputs, return_dict=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/CFG/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/CFG/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/CFG/lib/python3.11/site-packages/transformers/models/mistral/modeling_mistral.py", line 1033, in forward
    outputs = self.model(
              ^^^^^^^^^^^
  File "/opt/conda/envs/CFG/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/CFG/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/CFG/lib/python3.11/site-packages/transformers/models/mistral/modeling_mistral.py", line 761, in forward
    inputs_embeds = self.embed_tokens(input_ids)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/CFG/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/CFG/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/CFG/lib/python3.11/site-packages/torch/nn/modules/sparse.py", line 164, in forward
    return F.embedding(
           ^^^^^^^^^^^^
  File "/opt/conda/envs/CFG/lib/python3.11/site-packages/torch/nn/functional.py", line 2267, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper_CUDA__index_select)

I fixed it by isolating the attention mask and inputs and sending them to "device" in the example code listed in your github page 


`import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from transformers_cfg.grammar_utils import IncrementalGrammarConstraint
from transformers_cfg.generation.logits_process import GrammarConstrainedLogitsProcessor

# Detect if GPU is available, otherwise use CPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

model_path = "models/mistral"

# Load model and tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_path)
tokenizer.pad_token = tokenizer.eos_token 

model = AutoModelForCausalLM.from_pretrained(model_path).to(device)  
model.generation_config.pad_token_id = model.generation_config.eos_token_id

# Load json grammar
with open("grammars/json.ebnf", "r") as file:
    grammar_str = file.read()

grammar = IncrementalGrammarConstraint(grammar_str, "root", tokenizer)
grammar_processor = GrammarConstrainedLogitsProcessor(grammar)

# Define input prefixes
prefix1 = 'This is a valid json string for http request: '
prefix2 = 'This is a valid json string for shopping cart:  ' 

# Tokenize input prefixes
inputs = tokenizer([prefix1, prefix2], add_special_tokens=False, return_tensors="pt", padding=True)

# Move inputs to the correct device
input_ids = inputs["input_ids"].to(device)
attention_mask = inputs["attention_mask"].to(device)

# Generate with grammar constraints
output = model.generate(
    input_ids,
    attention_mask=attention_mask,  # Explicitly pass the attention mask
    max_length=50,
    logits_processor=[grammar_processor],
    repetition_penalty=1.1,
    num_return_sequences=1,
)

# Decode the generated output
generations = tokenizer.batch_decode(output, skip_special_tokens=True)
print(generations)


    """
    'This is a valid json string for http request:{ "request": { "method": "GET", "headers": [], "content": "Content","type": "application" }}
    'This is a valid json string for shopping cart:{ "name": "MyCart", "price": 0, "value": 1 }
    """`
