### ISSUE TITLE
Repetition brackets symbols

### ISSUE THREAD

**Issue by Viagounet** [epfl-dlab/transformers-CFG#92]
Hello!

First of all, thanks for working on this library, super handy. I was wondering if you were thinking about implementing the repetition bracket symbols (e.g _[a-z]{5,10}_)?

It is supported in [Llama.cpp](https://github.com/ggerganov/llama.cpp/blob/master/grammars/README.md#repetition-and-optional-symbols) but doesn't seem to be working with transformers-CFG right now, which makes it hard to easily switch from one framework to the other for some of my use-cases.

Thank you!

**Comment by Saibo-creator** [comment]
Hello @Viagounet  , thanks for raising this issue ! Compatibility with llama-cpp is indeed a priority. We will push on our side for this feature.

@nathanrchn Let's have a discussion on in our next meeting. This looks like the most important feature requested and we have also this #30  #21

**Comment by Saibo-creator** [comment]
@Viagounet  Thanks to the effort of @nathanrchn , this feature is now available, see #96
